### PR TITLE
feat(fscomponents): Add to fscomponents and PromoForm

### PR DESCRIPTION
**Pull request by alexandrvlasov**
Notes:

- Implement PromoForm with Formik

### CODE REVIEW

**Comment by Cauldrath** [comment]
Could you make a story.tsx file for this component?

**Comment by alexandrvlasov** [comment]
@Cauldrath I added a story.

**Comment by Cauldrath** [comment]
Not sure why, but when the story has the default value set, I can't edit the field and when I submit it gives me an error that it needs to be filled out. If I set the default value to undefined, it seems to work.

**Comment by alexandrvlasov** [comment]
@Cauldrath Please look again)

**Pull request merged**
