### PR TITLE
feat(fscomponents): Add formik, yup to fscomponents UpdateNameOrEmailFK

### PR DESCRIPTION
**Pull request by Bodrus**
Notes:
Implement SingleLineForm with Formik

### CODE REVIEW

**Comment by Cauldrath** [comment]
Conflict.

**Comment by Bodrus** [comment]
@Cauldrath Conflicts are resolved. Please look.

**Comment by Cauldrath** [comment]
Could you please add a story for this component?

**Comment by Bodrus** [comment]
@Cauldrath Story is added! Please look.

**Pull request merged**
