### PR TITLE
feat(flagship): lifecycle hooks

### PR DESCRIPTION
**Pull request by VanceHubb**
created by vance hu @VanceHubb (the account is about to be deactivated). 

### Backgrounds
Right now flagship's module patching scripts can only apply to a specific module in a fixed event (ios before link and android after link). And we cannot add project specific patches easily using current framework.

### Features
Replaced the current design with a more extensible lifecycle hook design. So a user can:
- Add project specific hooks by creating `./buildHooks` folder under project root path
- Execute the script in any of supported lifecycle events. Currently supporting: 'beforeCopyBoilerplate' | 'beforeLink' | 'beforeIOSPodInstall' | 'afterLink' | 'failed';
- Filter hooks by platforms / dependencies / dependency versions

### No Breaking Change
No breaking change - all the current patches are restructured in a way that behaves exactly same as the previous commit. Still we should scrutiny all the current patches to make them more restrictive though (add dependency version conditions, etc)

### Todo
- Revisit exiting patches to apply them more appropriate conditions
- Split some global fixes into separate hooks to make them more modular
- Add more lifecycle events if needed

### CODE REVIEW

**Comment by VanceHubb** [comment]
Note: a lot of script file changes are just adding metadata to the functions. No feature inside the functions are changed

**Comment by DavidRhodesBB** [comment]
This looks like a great enhancement Vance. How can we test it in the wild?

**Comment by VanceHubb** [comment]
@DavidRhodesBB All the current modules are converted the hook-style plugins so you can safely run flagship on any existing projects and expect nothing changed in generated files. To create a new plugin, try create a file under `{projectPath}/buildhooks` folder. Example:
```
const buildHooks: BuildHook[] = [
  {
    name: 'appcenter android patch',
    platforms: ['android'],
    lifeCycle: 'afterLink',
    packages: [{
      packageName: 'appcenter'
    }],
    script: configuration => {
      fs.update(
        path.android.mainApplicationPath(configuration),
        'new AppCenterReactNativePackage()',
        'new AppCenterReactNativePackage(application)'
      );
    }
  }
];
module.exports = buildHooks;
```

**Comment by VanceHubb** [comment]
bump. this would be helpful reducing patches we need in a few ongoing flagship upgrading processes

**Comment by VanceHubb** [comment]
superseded by this branch: https://github.com/brandingbrand/flagship/compare/develop...vancehu:hooks_master?expand=1

**Pull request closed without merging**
