### PR TITLE
feat(fsweb): Convert proxy to Typescript

### PR DESCRIPTION
**Pull request by Cauldrath**
Also moves the specific middleware attachments into their own files so they can be applied separately, runs compile-web and the proxy in parallel in dev mode, and will serve the app regardless of whether the proxy is running in prod mode

To test with PirateShip prod, run:
yarn
yarn ship:init-web
yarn ship:build-web
yarn ship:start-server-prod

For dev:
yarn
yarn ship:init-web
yarn ship:start-server-dev

Right now there are no environments configured to work with the proxy, though, as "commercecloud" isn't a valid data source type in PirateShip.

### CODE REVIEW

**Comment by deemaabdallah** [comment]
@bweissbart Can we please prioritize merging this PR please.

**Comment by deemaabdallah** [comment]
@Cauldrath conflicts please

**Comment by bweissbart** [comment]
@deemaabdallah - I'm on this. I have to wrap up merging develop into the flagship-10 branch (working on a Storybook issue now with that PR) and then Ben's PR should merge in cleanly.

**Comment by Cauldrath** [comment]
Oh, sorry, I merged from upstream and just resolved the yarn.lock file by using the FS10 version, deleting all the `@babel` entries and running yarn again. I'll see if storybook is broken after doing that.

**Comment by Cauldrath** [comment]
Redid the merge to use the develop -> feature/flagship-10 merge.

**Review by bweissbart — APPROVED** [review]
Tested. Looks good. 👍

**Pull request merged**
