### PR TITLE
Add keys ios

### PR DESCRIPTION
**Pull request by jcploucha**
**This PR removes hardcoded values in the `add-keys-ios.ts` script:**
* Reliance on a separate repo that houses iOS certificates and profiles
* Passwords

**The intended use case:** 
A project utilizing Flagship will contain the appropriate iOS certificates and profiles in a top-level directory in the project itself (see message in https://github.com/brandingbrand/flagship/commit/f3736fe3403b81c5657c9c01a082ef1290957dc3).

### CODE REVIEW

**Comment by AlexClineBB** [comment]
@skyeckstrom, Jon and I were discussing this change earlier. I'm concerned that it isn't backwards compatible with our current deployment process, so merging may break builds of legacy apps. Can you or someone on your team assist in getting the PR updated to maintain backwards compatibility so we're freed-up to begin migration of legacy apps with an easier timeline?

Let me know your thoughts.

**Comment by AlexClineBB** [comment]
@skyeckstrom, are you able to assist with completing this work? We're blocked on retiring the old repo until this is merged in.

**Comment by DavidRhodesBB** [comment]
Hi Jon - Is this PR still valid? I noticed Alex's comments above. Thanks much.

**Comment by bweissbart** [comment]
add-keys-ios and add-keys-android were removed in favor of scripts without hardcoded values in Flagship 5.

**Pull request closed without merging**
